### ISSUE TITLE
Sync Linguist Action is failing

### ISSUE THREAD

**Issue by DecimalTurn** [go-enry/go-enry#195]
Since Linguist 9.1.0, the Sync Linguist Action is failing:

eg.: 
https://github.com/go-enry/go-enry/actions/runs/13908903022

```ainsi
Run make code-generate
mkdir -p data && \
go run internal/code-generator/main.go
go: downloading gopkg.in/yaml.v2 v2.2.8
2025/03/17 20:11:38 failed to generate "data/content.go" from "internal/code-generator/assets/content.go.tmpl" - yaml: unmarshal errors:
  line 738: cannot unmarshal !!seq into string
  line 747: cannot unmarshal !!seq into string
exit status 1
make: *** [Makefile:2[5](https://github.com/go-enry/go-enry/actions/runs/13908903022/job/38918376542#step:9:6): code-generate] Error 1
\x1b[1;31mError: Process completed with exit code 2.
```

This is caused by the use of an array of strings for the `negative_pattern` instead of the usual string. Weirdly enough that has never been used before in the heuristics.yml file even if it is supported.

https://github.com/github-linguist/linguist/blob/1cc4b1a09f0bb64266386728966c1f839e386803/lib/linguist/heuristics.yml#L731-747

```yml
- extensions: ['.scm']
  rules:
  - language: Scheme
    pattern:
    - '(?:''[\(\*#]|\w->\w|\.\.\.[\s\)]|\([+\-:<>\/=~\)]|~>|[#`]\(|#:\w)'
    - '^\s*\((?:define\*?|import|library|lambda)'
    negative_pattern:
    - '\(#[\w-]+[!\?]'
    - '[\)\]"_]\s*(?:[\*\+\?]|@\w)'
  - language: Tree-sitter Query
    pattern:
    - '\(#[\w-]+[!\?]'
    - '[\)\]"_]\s*(?:[\*\+\?]|@\w)'
    - '(?:^\s*\w+:\s*[\(\[\"])'
    - '\(#(?:set!|(?:not-)?(?:any-of|match)\?)'
    negative_pattern:
    - '\([+\-:<>\/=~\)]'
```
